Ajax
yukihamu1206/twitter pull request #10
Opened 2020-03-06 05:45 UTC by yukihamu1206

いいねの部分と、showの変数をなるべくcontrollerに書くようにしました。

2020-03-06 10:20 UTC, osakana9114 requested changes
先ほどの振り返りの内容も含め、いくつかコメントしました！

2020-03-06 10:20 UTC, osakana9114 commented on app/Http/Controllers/TweetsController.php
> +                'user' => $timeline->user,
@yukihamu1206 
`$list['user']` は画面 （resources/views/tweets/index.blade.php）で使っていないのでいらないとおもいます。
"favorite"も同様

2020-03-06 10:20 UTC, osakana9114 commented on app/Http/Controllers/TweetsController.php
> +     * @return \Illuminate\Http\RedirectResponse
@yukihamu1206 
returnの型が実装と異なっています。
viewを返しているので `@return \Illuminate\Contracts\View\Factory|\Illuminate\View\View` となるはず👩‍💻

その他のメソッドも同様

2020-03-06 10:20 UTC, osakana9114 commented on resources/views/tweets/show.blade.php
> +                            <button type="button" class="btn p-0 border-0 text-danger favorite"><i class="fas fa-heart fa-fw"></i></button>
@yukihamu1206 
DOM要素自体を分岐させるのではなく、可変な値のみを動的に入れたほうが良いです。
```
<button type="button" class="btn p-0 border-0 text-danger favorite"><i class="fas fa-heart fa-fw"></i></button>
```
は一行だけにして、

```
<button type="button" class="btn p-0 border-0 text-danger favorite" data-favorite="{{ $いいね状態を表す変数 }}"><i class="{{ $いいね状態に基づくクラス名 }}fa-heart fa-fw"></i></button>
```

☝️みたいなかんじ。
jQueryで `data-favorite` によってリクエストするエンドポイントを分岐、
結果によってクラス名を変えて❤️の色を変える

2020-03-06 10:20 UTC, osakana9114 commented on app/Http/Controllers/FavoritesController.php
> -            return back();
@yukihamu1206 
いいねを付けたあと、
1. 総カウントがいくつになったのかを取得
2. レスポンスのJSONに入れて画面に返す

2020-03-06 10:20 UTC, osakana9114 commented on app.json
> +{
@yukihamu1206 
app.jsonは、現状ではなくてもいいぽいです😂
#11

2020-03-09 03:07 UTC, osakana9114 commented
@yukihamu1206 
storage/debugbar 配下のファイルが含まれてしまっているみたいなので、これは除外しましょう🚫
Laravelが生成するキャッシュファイルが格納されているところです。

2020-03-09 07:44 UTC, yukihamu1206 commented
【完成したところ】
鯵坂さんにレビューしていただいたところを修正して、twitters/showは完成しました。

```php
 <div class="d-flex align-items-center">
                            <button type="button" class="btn p-0 border-0 text-danger favorite" id="favorite" data-favorite="{{optional($user_favorite)->id }}"><i class="fa-heart fa-fw {{ $user_favorite ? 'fas' : 'far' }}" id="favorite_i"></i></button>

                        <p class="mb-0 text-secondary favorite_count">{{ $favorite_count }}</p>


                                <script>
                                    $(function() {
                                        $(".favorite").click(function(e) {
                                            if($(this).children('i').hasClass('far')) {
                                                $.ajax({
                                                        url: "{{ url('/favorites') }}",
                                                        data: {
                                                            _token: "{{ csrf_token() }}",
                                                            tweet_id: "{{ $tweet->id }}",
                                                        },
                                                        type: "POST",
                                                        success: function (data) {
                                                            if (data['result'] === true) {
                                                                let heart = $(".fa-heart");
                                                                heart.removeClass('far');
                                                                heart.addClass('fas');
                                                                $('#favorite').attr('data-favorite',data['user_favorite_id']);
                                                                $(".favorite_count").text(data['favorites_count']);

                                                            } else {
                                                                error_log('errorrrrrr');
                                                            }
                                                         }
                                                    });
                                            }else {
                                                let element = document.getElementById('favorite');
                                                let favorite =  element.dataset.favorite;
                                                $.ajax({
                                                    url: '/favorites/' + favorite,
                                                    data: {
                                                        _token: "{{ csrf_token() }}",
                                                        tweet_id: "{{ $tweet->id }}",
                                                    },
                                                    type: "DELETE",
                                                    success: function (data) {
                                                        if (data['result'] === true) {
                                                            let heart = $(".fa-heart");
                                                            heart.removeClass('fas');
                                                            heart.addClass('far');
                                                            $(".favorite_count").text(data['favorites_count']);
                                                            $('i').data('favorite',"{{optional($user_favorite)->id}}");

                                                        } else {
                                                            error_log('errorrrrrr');
                                                        }
                                                    }
                                                });
                                            }
                                        });
                                    });
                              </script>
```

【わからなかったところ】

- editorconfigが適応されているか

- twitters/indexと、users/showの投稿をforeachで表示しているところのいいねの処理

tweets.blade.php

```a.blade.php

  @foreach($lists as $list)
                        <div class="col-md-8 mb-3">
                            <div class="card">
                                <div class="card-haeder p-3 w-100 d-flex">
                                      <img src="{{ asset('storage/profile_image/'.$list['profile_image']) }}" class="rounded-circle" width="50" height="50">
                                    <div class="ml-2 d-flex flex-column">
                                        <p class="mb-0">{{ $list['user_name'] }}</p>
                                        <a href="{{ url('users/' .$list['user_id']) }}" class="text-secondary">{{ $list['screen_name'] }}</a>
                                    </div>
                                    <div class="d-flex justify-content-end flex-grow-1">
                                        <p class="mb-0 text-secondary">{{ $list['created_at'] }}</p>
                                    </div>
                                </div>
                                <div class="card-body">
                                    {!! nl2br(e($list['tweet_text'])) !!}
                                </div>

                                <div class="card-footer py-1 d-flex justify-content-end bg-white">
                                    @if ($list['user_id'] === Auth::user()->id)
                                        <div class="dropdown mr-3 d-flex align-items-center">
                                            <a href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <i class="fas fa-ellipsis-v fa-fw"></i>
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                                <form method="POST" action="{{ url('tweets/' .$list['tweet_id']) }}" class="mb-0">
                                                    @csrf
                                                    @method('DELETE')

                                                    <a href="{{ url('tweets/' .$list['tweet_id'] .'/edit') }}" class="dropdown-item">編集</a>
                                                    <button type="submit" class="dropdown-item del-btn">削除</button>
                                                </form>
                                            </div>
                                        </div>
                                    @endif
                                    <div class="mr-3 d-flex align-items-center">
                                            <a href="{{ url('tweets/' .$list['tweet_id']) }}"><i class="far fa-comment fa-fw"></i></a>
                                            <p class="mb-0 text-secondary">{{ $list['comment_count'] }}</p>
                                    </div>


                                    <div class="d-flex align-items-center">
                                                <button type="button" class="btn p-0 border-0 text-danger favorite"><i class="fa-heart fa-fw {{ $list['user_favorite'] ? 'fas' : 'far' }}" id="favorite_i" data-favorite="{{ optional($list['user_favorite'])->id }}"></i></button>

                                            <p class="mb-0 text-secondary favorite_count">{{ $list['favorite_count'] }}</p>
                                    </div>

                                </div>
                            </div>
                        </div>
                    @endforeach

  <script>
                $(function() {
                    $(".favorite").click(function (e) {
                        if ($(this).children('i').hasClass('far')) {
      [...]

2020-03-09 09:08 UTC, osakana9114 commented
@yukihamu1206 
> editorconfigが適応されているか

コードフォーマットについて、以下の2ファイルに適用してpushしてみました。
- app/Http/Controllers/FavoritesController.php
- resources/views/tweets/index.blade.php

**⌥⌘L** でフォーマットできるので試してみてください。
[Reformat and rearrange code](https://www.jetbrains.com/help/phpstorm/reformat-and-rearrange-code.html?keymap=secondary_default_for_macos)

また FavoritesController の store() と destroy() はPHPDocも修正してみました。
コードの下に波線がでている行にカーソルを合わせると左のほうに💡がでてくるので、それを押すと修正案を表示してくれます。
それに従ってクリックすれば自動で修正してくれます✊

　
> 今の状態だと、全投稿にいいねがつく

一覧画面ではツイートが複数表示されているので、いいねボタンを押したときに対象のツイートIDを渡せていないことが原因です。
TODOコメントを入れたところを修正してみてください👩‍💻

```
$.ajax( {
  url: "{{ url('/favorites') }}",
  data: {
      _token: "{{ csrf_token() }}",
      // TODO: 正しい tweet_id が取れていない ⇨ いいねボタンのDOMにツイートのIDも持たせておく
      tweet_id: "{{ $list['tweet_id'] }}",
  },
```

2020-03-09 12:44 UTC, yukihamu1206 commented
twitters/show.blade.php

いいねをつけて、いいねを取り消して、もう一度いいねをつけることはできるのですが、
２回目のいいねの取り消しのときに、1回目のdata-favoriteの値を参照してしまうので、エラーになる

 ```php
 let favorite = button.data('favorite'); 
```
ここで持ってくるIdが一度目に作られたもの

- data-favoriteは更新されていることを確認

```php.blade.php


                            <div class="d-flex align-items-center" >
                                <button type="button" class="btn p-0 border-0 text-danger favorite" data-tweet_id="{{ $list['tweet_id'] }}" data-favorite="{{ optional($list['user_favorite'])->id }}"><i
                                        class="fa-heart fa-fw {{ $list['user_favorite'] ? 'fas' : 'far' }}"
                                        id="favorite_i"></i>
                                </button>

                                <p class="mb-0 text-secondary favorite_count" data-tweet_id="{{ $list['tweet_id'] }}">{{ $list['favorite_count'] }}</p>
                        </div>

                        </div>
                    </div>
                </div>
            @endforeach


            <script>
                $( function () {
                    $( ".favorite" ).click( function ( e ) {
                        let button = $(this);
                        let favorite_count = button.parent().find('p');
                        if ( $( this ).children( 'i' ).hasClass( 'far' ) ) {
                             let tweet_id = $(this).data('tweet_id');
                            $.ajax( {
                                url: "{{ url('/favorites') }}",
                                data: {
                                    _token: "{{ csrf_token() }}",
                                    // TODO: 正しい tweet_id が取れていない ⇨ いいねボタンのDOMにツイートのIDも持たせておく
                                    tweet_id: tweet_id,
                                },
                                type: "POST",
                                success: function ( data ) {
                                    if ( data['result'] === true ) {
                                        button.children('i').removeClass( 'far' );
                                        button.children('i').addClass( 'fas' );
                                        button.attr( 'data-favorite', data['user_favorite_id'] );
                                        favorite_count.text( data['favorites_count'] );

                                    } else {
                                        console.log( 'errorrrrrr' );
                                    }
                                }
                            })
                        } else {
                             let favorite = button.data('favorite');
                            let tweet_id =  button.data('tweet_id');
                            $.ajax( {
                                url: '/favorites/' + favorite,
                                data: {
                                    _token: "{{ csrf_token() }}",
                                    tweet_id: tweet_id,
                                },
                                type: "DELETE",
                                success: function ( data ) {
                                    if ( data['result'] === true ) {
                                        button.children('i').removeClass( 'fas' );
                                        button.children('i').addClass( 'far' );
                                        button.attr( 'data-favorite', "" );
                                        favorite_count.text( data['favorites_count'] );
                                    } else {
                                        console.log( 'errorrrrrr' );
                                    }
                                }
                            } );
                        }
                    } );
                } );
            </script>
```

2020-03-10 02:57 UTC, takakd commented
@yukihamu1206 
jQueryのdataキャッシュの問題のようですね。
https://qiita.com/toshiharu-irie/items/e7f803085000c4008f51

```
let favorite = button.data('favorite'); 
```

取得、設定ともにattr, もしくはdatasetに統一すると良いです。

2020-03-10 03:15 UTC, osakana9114 commented
@yukihamu1206 
これも参考に📝
https://w3g.jp/blog/jquery-data-attr-cache

`data` 属性は↓のようにしても
```
button.data('favorite', data['user_favorite_id']);
```
HTML上には現れませんが、データ自体は置き換わっています。
console.log で出してみるとわかります👍

2020-03-10 04:59 UTC, yukihamu1206 commented
@osakana9114 @takakd 
いいね実装できて完成しました！ありがとうございます。

2020-03-12 06:07 UTC, osakana9114 approved these changes

2020-03-12 06:07 UTC, merged